version: "3.8"

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --slow-query-log=1 --long-query-time=10 --slow-query-log-file=/var/log/mysql/mysql-slow.log
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./logs:/var/log/mysql

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch_data:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ELASTIC_USERNAME: admin
      ELASTIC_PASSWORD: admin

  graylog:
    image: graylog/graylog:5.1.4
    entrypoint: /usr/bin/tini -- wait-for-it admin:admin@elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - elasticsearch
      - mongo
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      GRAYLOG_PASSWORD_SECRET: adminadminadminadminadmin
      GRAYLOG_ROOT_PASSWORD_SHA2: 29d2fa5cd7463899008779a74977369729b4a806ba4f39056097d15c9f58df48
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://admin:admin@elasticsearch:9200

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    restart: always
    user: root
    volumes:
      - ./configs/graylog.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/mysql

volumes:
  mysql_data: {}
  elasticsearch_data: {}
